### PR TITLE
added damage object

### PR DESCRIPTION
**Pull request by matt-wirtz**
Added damage object to hold information regarding existing damages of vehicles. Included the damage object into the asset object.

### CODE REVIEW

**Review by edwinvandenbelt — CHANGES_REQUESTED** [review]
Thank you Matthias! Nice piece of work! I have a few questions, please have a look at them. I'm always a bit straight-forward, describing how I think it should be. 
* The only real issue that will result in frustrated users is the dash in the enums.
* I think it will be a missed chance if we don't add the reporting of issues using the POST /support. What harm will be done if we add it anyhow?

**Comment by matt-wirtz** [comment]
Thanks Edwin for your review. I committed again.

As vehicle parts/components I have now:
FRONT, REAR, LEFT, RIGHT, TOP, BOTTOM, INTERIOR, TIRE, ANCILLARY, OTHER

I didn't include:
- ENGINE: what kind of damages regarding the engine would you be able to see from outside? Additionally if the engine has issues the car sharer should not allow the car to be used anymore. So I think it's not necessary to include this part.
- SEAT: I think that is included in INTERIOR
- LEFT_FRONT, RIGHT_FRONT, REAR_LEFT, REAR_RIGHT: They overlap with LEFT, RIGHT, FRONT, REAR and therefore I think it adds uncertainty as where does LEFT_FRONT ends and where does LEFT start and so on. In my discussions it became clear that car sharers typically tend to have sophisticated methods of recording the precise location of damages. It's possible e.g. to mark the location of damages on a wire frame picture of the vehicle with a red dot. It's always possible to reduce precision and only expose the vehicle part/component. And here it's only differentiated between LEFT, RIGHT, FRONT, REAR. So I would suggest to leave the vehicle part/component enum to LEFT, RIGHT, FRONT, REAR. If it's necessary to further differentiate the left side into front, middle and rear I would rather suggest to add another level of location attribute e.g. sub-part/sub-component. 
Does this make sense?

The pictures of the damage don't need to be exposed when planning or booking. But they must be exposed when preparing the trip (POST /legs/{id}/event) before "SET_IN_USE" can be triggered. So I think they need to be part of the damage object. But maybe I overlook something here.

**Comment by matt-wirtz** [comment]
Regarding the pictures showing the damages:
Before starting to drive the vehicle one has to confirm that all visible/obvious damages are already part of the existing vehicle damages list. Otherwise the hotline of the TO must be informed about any additional damages.
For the process of checking all damages I think it's very important to have the pictures as an additional aid available. So the pictures need to be available in the trip execution phase, not planning or booking phase.
To get into the trip execution phase, the booking phase needs to be completed. In the booking phase the contract between user and TO is established, terms&conditions agreed on. Are there any GDPR topics regarding the pictures of damages left?
The pictures of course should not disclose who made the picture or show any persons on it. But I think that is the responsibility of the TO.

Should I include the info that the damage object should only be exposed when in the trip execution phase?

I do opt for skipping the reporting part. For the car sharers this approach doesn't fulfill their requirements regarding precise location of the damage and therefore might raise the probability of reporting the same damage repeatedly.

**Comment by edwinvandenbelt** [comment]
It makes sense, let's keep the URLs in the damage object. We have to think about how to report the damage in the next version. Could you also write a page on the wiki on how to use the damage object? I've added you to the list of maintainers of this github site.

**Review by edwinvandenbelt — APPROVED** [review]

**Pull request merged**
