### PR TITLE
244 regions

### LINKED ISSUE #244: [FEATURE REQUEST] regional aspects
## Is your feature request related to a problem? Please describe.
If you're an operator with a lot of regions, per region other assets, other prices, other stations, shouldn't be there any facility to filter?

## Urgency
Major (the TOMP API works as advertised but this is really neccessary to implement), because there will be a huge amount of data sent to the MP (f.i. using pricing-plans) without the MP knowing which price to use.

## Describe the solution you'd like
Add query filters to available-asssets, operating-calendar, operating-hours and pricing-plans. And add a regionId to all of the results.

## Describe alternatives you've considered
Only adding regionIds => still too much data

### PR DESCRIPTION
**Pull request by edwinvandenbelt**
closes #244

### CODE REVIEW

**Comment by jensfrandsen** [comment]
Isn't this change solved by namespacing TOMP by region?

**Comment by edwinvandenbelt** [comment]
Possibly. But it cannot be derived from the GBFS feed

Van: Jens Kjærby Frandsen <notifications@github.com>
Verzonden: Wednesday, 4 November 2020 09:09
Aan: TOMP-WG/TOMP-API <TOMP-API@noreply.github.com>
CC: Edwin van den Belt <edwinvandenbelt@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [TOMP-WG/TOMP-API] 244 regions (#280)


Isn't this change solved by namespacing TOMP by region?

**Comment by edwinvandenbelt** [comment]
Sorry Jens, in the mail I thought it had to do with the GBFS discussion. This functionality allows also to specify things per station (opening hours etc).

**Comment by piotrj** [comment]
@jensfrandsen I guess this solution doesn't disqualify having namespaces URLs. So TO can decide whether to have 1 namespace/system with multiple regions or multiple namespaces/systems with 1 region.

@edwinvandenbelt regarding pricing endpoint - if in fact there is multiple regions and each region has its own pricing but the request to `pricing_plans` is done without the `region` parameter then I guess there response should contain pricings for all regions. But then there is no way to know which pricing applies for which region. Do you have any ideas on how to solve that?

**Pull request merged**
