### PR TITLE
Directed the error messages to the TOMP Wiki

### PR DESCRIPTION
**Pull request by pimmeh**
I went through all the endpoints in the YAML and it either comes down to no permission for the operation, the booking is not found of the booking is in the wrong state. I edited the API so that it links to the TOMP-wiki where a user can look up certain error codes. I also put a little text in the wiki that we want to know what errors we are missing and if we are, we want to know about them. I described it like:

"When an error is not present in the table below but you do want to return an error code to your clients, please use the error codes x500 and onwards and create an issue on our GitHub page. We will then look at the error to see if we can incorporate it into this table. DO NOT use the reserved range from x100 to x499!"

Please look at my changes, also for the wiki.

### CODE REVIEW

**Comment by ARBaart** [comment]
Hey Pim! Looks good, but can you create this pull request into `develop-minor` or `develop-major` instead of directly into master?

**Comment by pimmeh** [comment]
@ARBaart I think I did it, but now I have some sort of merge conflict? Did I do it right?

**Comment by ARBaart** [comment]
Yes thanks, I’ll fix the merge conflict 🤗

**Comment by pimmeh** [comment]
> 
> 
> I'm missing the attribute 'errorCode' in the error object.

Ehm, it's there in line 1544?

**Comment by edwinvandenbelt** [comment]
Sorry Overlooked it!

**Pull request merged**
